/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as ScanReceiptRouteImport } from './routes/scan-receipt'
import { Route as ScanFridgeRouteImport } from './routes/scan-fridge'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AddRouteImport } from './routes/add'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanReceiptRoute = ScanReceiptRouteImport.update({
  id: '/scan-receipt',
  path: '/scan-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanFridgeRoute = ScanFridgeRouteImport.update({
  id: '/scan-fridge',
  path: '/scan-fridge',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/add': typeof AddRoute
  '/alerts': typeof AlertsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recipes': typeof RecipesRoute
  '/scan-fridge': typeof ScanFridgeRoute
  '/scan-receipt': typeof ScanReceiptRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/item/$id': typeof ItemIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/add': typeof AddRoute
  '/alerts': typeof AlertsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recipes': typeof RecipesRoute
  '/scan-fridge': typeof ScanFridgeRoute
  '/scan-receipt': typeof ScanReceiptRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/item/$id': typeof ItemIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/add': typeof AddRoute
  '/alerts': typeof AlertsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recipes': typeof RecipesRoute
  '/scan-fridge': typeof ScanFridgeRoute
  '/scan-receipt': typeof ScanReceiptRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/item/$id': typeof ItemIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/add'
    | '/alerts'
    | '/inventory'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/recipes'
    | '/scan-fridge'
    | '/scan-receipt'
    | '/shopping'
    | '/terms'
    | '/item/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/add'
    | '/alerts'
    | '/inventory'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/recipes'
    | '/scan-fridge'
    | '/scan-receipt'
    | '/shopping'
    | '/terms'
    | '/item/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/add'
    | '/alerts'
    | '/inventory'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/recipes'
    | '/scan-fridge'
    | '/scan-receipt'
    | '/shopping'
    | '/terms'
    | '/item/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AddRoute: typeof AddRoute
  AlertsRoute: typeof AlertsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecipesRoute: typeof RecipesRoute
  ScanFridgeRoute: typeof ScanFridgeRoute
  ScanReceiptRoute: typeof ScanReceiptRoute
  ShoppingRoute: typeof ShoppingRoute
  TermsRoute: typeof TermsRoute
  ItemIdRoute: typeof ItemIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-receipt': {
      id: '/scan-receipt'
      path: '/scan-receipt'
      fullPath: '/scan-receipt'
      preLoaderRoute: typeof ScanReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-fridge': {
      id: '/scan-fridge'
      path: '/scan-fridge'
      fullPath: '/scan-fridge'
      preLoaderRoute: typeof ScanFridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AddRoute: AddRoute,
  AlertsRoute: AlertsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RecipesRoute: RecipesRoute,
  ScanFridgeRoute: ScanFridgeRoute,
  ScanReceiptRoute: ScanReceiptRoute,
  ShoppingRoute: ShoppingRoute,
  TermsRoute: TermsRoute,
  ItemIdRoute: ItemIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
